### ISSUE TITLE
Undesirable unload eventlistener

### ISSUE THREAD

**Issue by svgmuc** [DLXPlugins/wp-ajaxify-comments#6]
## What is the desired behavior?

Replace 'unload' event listener. I have tested 'pagehide' without any noticeable downsides. 

## What is the actual behavior?

'unload' event listeners are marked as issues in PageSpeed Insights. They recommend using 'pagehide' instead.

## Steps to reproduce undesired behavior:

1. Install and activate the plugin
2. Visit the Settings tab
3. Enable Ajaxify Comments and Save Options
4. Navigate to https://pagespeed.web.dev/
5. Enter the URL of your WordPress instance
6. Click Analyze

## Additional Comments
PageSpeed Insights output:

Registers an unload listener: 
The unload event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use pagehide or visibilitychange events instead.

**Comment by svgmuc** [comment]
Affected file is dist/wpac-frontend-js.js

**Comment by ronalfy** [comment]
This no longer appears to be an issue.
