### ISSUE TITLE
admin-ajax.php not working in admin: [BUG] While plugin activated, all requests to admin-ajax.php fails

### ISSUE THREAD

**Issue by wiesys** [DLXPlugins/wp-ajaxify-comments#7]
## What is the desired behavior?

AJAX requests in the admin area should work as before when the plugin is active.

## What is the actual behavior?

All AJAX requests to admin-ajax.php fails with error 500, and in the debug log it shows:
```
[07-Feb-2024 07:01:14 UTC] PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) in /home/latvianson/latviansonline.com/wp-includes/plugin.php on line 173
```

## Screenshots or Video
Heres the video demo: https://www.loom.com/share/d04b6b7272ad40119ac4b6cade6def81

**Comment by ronalfy** [comment]
I watched the video. This seems like a 500 error behind the scenes. I'm going to assume this is fixed as I can't duplicate it, but please reopen if you can still duplicate this error with the latest version.
